In [1]:
import numpy as np

In [2]:
u = np.array([1, 0])

In [3]:
v = np.array([0, 1])


In [4]:
z = u + v
z

array([1, 1])

In [5]:
u*v

array([0, 0])

In [6]:
u = [1,0]

In [7]:
v = [0, 1]

In [8]:
z = []

In [9]:
for n, m in zip(u, v):
    z.append(n+m)
z

[1, 1]

In [10]:
arr = np.random.randn(3, 4)
arr

array([[-1.26542116,  0.76856898,  1.60962087,  0.58637682],
       [ 0.6418021 , -0.43399165, -0.65742709,  0.22177583],
       [-1.58482914, -1.75523066,  0.46314355,  1.24029597]])

In [11]:
arr.shape

(3, 4)

In [12]:
arr.size

12

In [13]:
arr.ndim

2